modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Samarium150/StructuresCompass/issues"
license="GNU GENERAL PUBLIC LICENSE Version 3"

[[mods]]
    modId="structurescompass"
    version="${file.jarVersion}"
    displayName="Structures Compass"
    updateJSONURL="https://raw.githubusercontent.com/Samarium150/StructuresCompass/main/docs/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/structures-compass"
    logoFile="logo.gif"
    authors="Samarium, SnightW"
    description='''
    Search for a specific structure.
    '''
